preload = ["./replit.toml.js"]
jsx = "react-jsx"
jsxImportSource = "react"

[loader]
".ts" = "ts"
".tsx" = "tsx"
".js" = "js"
".mjs" = "js"
".mts" = "ts"
".codepark" = "js"
".json" = "json"
".toml" = "toml"
".replit" = "toml"
".park" = "toml"
".wasm" = "wasm"

[install]
auto = true
